Algoritmo "Meu primeiro algoritmo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Victor Matheus Marinho de Souza
// Data atual  : 02/03/2021
Var
// Seção de Declarações das variáveis
nota: inteiro;




Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
nota <- 100

escreva("Resultado: ", nota)

Fimalgoritmo